### ISSUE TITLE
[Question] Global Menu

### ISSUE THREAD

**Issue by tttom64** [cromnix/pamac-classic#10]
This is less of an issue/request and more of a general question. Don't take this as a criticism - I just want to understand this better. 
Why has pamac never used GNOME's global menu and instead put the preferences, about, etc. in a hamburger menu? In every other gtk3 app I've used, the global menu is always used for quit/about/preferences whereas the hamburger, if there is one, is for specific options or quick actions. For example, Epiphany has the zoom controls, new tab, print button, all in the hamburger menu, while history, preferences, keyboard shortcuts are in the global menu. There is some overlap with new window appearing in both.

**Comment by tabepic** [comment]
Not trying to speak for @cromerc, but [manjaro/pamac](https://github.com/manjaro/pamac) would probably be a better place to ask, as this is just a fork of it (pretty much all design choices, including this one, were made before the fork)

**Comment by cromerc** [comment]
@tabepic is right. I only forked from pamac at 5.x.x, I did not create pamac. So it is impossible for me to talk about why it was designed this way.

As far as the "global" menu, not sure what you are talking about. The only menu that I have when I run pamac is the hamburger menu, I don't see any other menu. My desktop environment is cinnamon under Artix Linux and mate under Cromnix Linux, and under both of those I only have the hamburger menu.

**Comment by tabepic** [comment]
Did a bit of ~~research~~ Google-fu and it seems that the "global menu" is the menu at the top of the screen in DE's such as Unity (shown in picture) ![Global Menu](http://cloud.addictivetips.com/wp-content/uploads/2011/10/Global-Menu.jpg)

I'd assume @tttom64 means the menubar (usually showing menus such as File, Edit, etc), which neither pamac nor pamac-classic have anyways.

**Comment by cromerc** [comment]
Well good to know, never really learned the terms for the "unity" and "gnome 3" interfaces. When unity and gnome 3 came along I jumped ship to cinnamon and mate.

**Comment by tttom64** [comment]
@tabepic @cromerc  That's not quite what I meant by global menu. GNOME's global menu is just a single dropdown like this:

![screenshot from 2017-10-31 17-39-42](https://user-images.githubusercontent.com/13117753/32210654-ce815cdc-be06-11e7-9f13-a843c72344f1.png)
![screenshot from 2017-10-31 17-41-19](https://user-images.githubusercontent.com/13117753/32210655-cefcfa7c-be06-11e7-81a8-41c7d50c0d74.png)

I'll quickly install XFCE to see what this looks like there.

**Comment by cromerc** [comment]
I don't think it will be worth implementing: http://www.omgubuntu.co.uk/2017/09/gnome-global-menu-extension-discontinued

The gnome global menu extension is discontinued as of last month, it currently only works in xorg and as systems start to transition to wayland or mir it does not work.

**Comment by tabepic** [comment]
@tttom64 I see.
I don't have much experience with the GTK 3 global menu, nor GNOME (XFCE is my DE of choice), however I do agree that the decision to make it a hamburger menu is odd.

**Comment by tabepic** [comment]
Alright, I made a quick edit of pamac-manager's ui files, and came up with this:
![edited-1](https://user-images.githubusercontent.com/9892196/32253881-ff2d1c5c-be62-11e7-9639-191144ffe632.png)
![edited-2](https://user-images.githubusercontent.com/9892196/32253882-02079542-be63-11e7-86eb-f01cc72c088a.png)

For comparison:
![orig-2](https://user-images.githubusercontent.com/9892196/32253886-0dbb9aaa-be63-11e7-8ae3-242d2b8aa466.png)

Is this the change you would like to see? Or is there something I'm missing?

**Comment by tttom64** [comment]
@tabepic has it right. @cromerc the extension you linked to isn't the same as gnome's global menu - it's the more traditional menubar (file edit view etc) like in gimp or inkscape. 

I can think of a few reasons to do or not do this:
Pros: More streamlined for GNOME users, Ubuntu MATE 17.10 users (I think), and anyone using the vala appmenu for xfce, mate or budgie. More consistent with other gtk3 apps. Better design, since global actions like about and preferences shouldn't be in a hamburger.
Cons: Since this is a classic version, a UI change might not be preferable. May confuse some users.

**Comment by tabepic** [comment]
I may be oblivious to other needed code changes, but to me this seems to be a very trivial change (I've never even touched vala before, and used Glade about twice in my life)
If it is as simple as I think it is, then I agree that it should be implemented this way.

In case anyone cares, I posted the patch I made [here](https://gist.github.com/tabepic/c45c83b34b9bd4129f651e522d88bd04)

**Comment by cromerc** [comment]
What I can do is add some code in combination with your changes that will make it the choice of the person compiling. They can choose to compile with  the hamburger menu or the global menu.

**Comment by tabepic** [comment]
Sounds good to me. 👍

**Comment by cromerc** [comment]
Alright I have done the implemented it: https://github.com/cromnix/pamac-classic/commit/90ffcb5fd3609b1c89b7bb8965603a9611fe0e6e

Please report back if there are any issues.
For people that want the classic hamburger menu they just need to add the "enable hamburger" flag when they are building.

**Comment by cromerc** [comment]
Oops forgot to mention, when the global menu is built it has a new "Quit" option in it. The quit option is not in the hamburger menu though.

**Comment by tttom64** [comment]
The 'global' menu still isn't working on GNOME. What the change currently does is move the hamburger menu into an icon menu. For gtk3 apps, the icon menu is usually a fallback (I think) for when the DE doesn't provide a global menu (so all except GNOME and some instances of mate and xfce) or the user specifies not to have one.

Current behavior: The icon menu is always used. The global menu is still empty.
![menureal](https://user-images.githubusercontent.com/13117753/32366691-1c2efe68-c077-11e7-8810-1687da0d2ebc.jpg)

Ideal behavior: Icon menu is only used as a fallback if global menu is disabled or unavailable. Global menu should be populated. (crappy mockup)
![menumockup](https://user-images.githubusercontent.com/13117753/32366690-19dbb7dc-c077-11e7-97b7-2f19d7c2357d.jpg)

**Comment by cromerc** [comment]
Alright, I think I found the solution: https://developer.gnome.org/ApplicationMenu/

I will try this out later today.

**Comment by cromerc** [comment]
@tttom64 I believe that it is working the way you want now. Sorry it took so long, I had to setup an arch linux virtualbox with a gnome environment to test as I worked.

The relevant commit: https://github.com/cromnix/pamac-classic/commit/83b7223d7b0f1426a83b9a83ef526fe5ac3e5826
This should be fixed in 6.5.1.

**Comment by tttom64** [comment]
Yes, this works perfectly. Thanks for putting in the time for what seems like such a small issue.

**Comment by cromerc** [comment]
Good to hear. I don't have much experience with gtk apps so it was interesting to experiment a bit.
