### ISSUE TITLE
Uninstalling does not work from update dialog

### ISSUE THREAD

**Issue by RalphBike** [cromnix/pamac-classic#18]
Using 6.6.3 I get this behaviour:
-Pamac notifies my about an update of an AUR package
-I decide that I do not need that piece of software anymore, I open the context menu and click remove.
-Nothing happens.

What I would expect: 
-Update of the icon (from update to remove)
-Change of the Context menu (remove is disabled, install is enabled)

**Comment by cromerc** [comment]
Alright, this bug has been fixed.
