### ISSUE TITLE
[Question] AUR package

### ISSUE THREAD

**Issue by tabepic** [cromnix/pamac-classic#2]
Are there plans to add this to the AUR?
If not, I'd be happy to make a package for it and maintain it.

EDIT: Alright, I made the package. It is available in the [AUR](https://aur.archlinux.org/packages/pamac-classic/).

(Side note: thank you very much for making this fork, I hope it stays maintained for as long as pamac is!)

**Comment by cromerc** [comment]
> Are there plans to add this to the AUR?
> If not, I'd be happy to make a package for it and maintain it.

I hadn't planned on adding it to the AUR so feel free to do so yourself. I recommend calling the package pamac-classic.

> (Side note: thank you very much for making this fork, I hope it stays maintained for as long as pamac is!)

No problem, I think this needed to be forked since from pamac 6.0 and on they plan to convert it into a store instead of a basic package manager. I have already applied all the relevant patches/fixes that effect 5.1.x, now it will just be a matter of keeping up to date on fixes.

**Comment by tabepic** [comment]
> I hadn't planned on adding it to the AUR so feel free to do so yourself. I recommend calling the package pamac-classic.
Alright, pamac-classic it is.
> I have already applied all the relevant patches/fixes that effect 5.1.x, now it will just be a matter of keeping up to date on fixes.
Does this mean that relevant "additions" (such as mentioned in  #3) would be backported as well?

**Comment by cromerc** [comment]
> Does this mean that relevant "additions" (such as mentioned in #3) would be backported as well?

As long as it doesn't stop it from being a basic package manager, I have no problems with backporting features into this.

**Comment by tabepic** [comment]
> As long as it doesn't stop it from being a basic package manager, I have no problems with backporting features into this.

Awesome, thanks!

**Comment by cromerc** [comment]
Considering the AUR package exists and it is also now available in both Cromnix and Artix Linux repos, I will close this.
