### ISSUE TITLE
[Bug] Cache cleaning settings not saving

### ISSUE THREAD

**Issue by tabepic** [cromnix/pamac-classic#4]
See [manjaro/pamac #306](https://github.com/manjaro/pamac/issues/306)

The cache cleaning settings don't save.
Actually, I'm not sure that that automated cache cleaning even works in pamac v5/classic, as it was added somewhat recently (it used to be only manual)

**Comment by cromerc** [comment]
Before I go digging around to see what is happening, the auto cache cleaning doesn't work on non-systemd systems. This means that if you use openrc, s6, svinit, runit, etc, it will not work. This also means it does not work under Artix, Cromnix, nor Manjaro OpenRC. What distro do you use? and do you use Systemd?

**Comment by tabepic** [comment]
@cromerc I'm on Arch, using systemd.

**Comment by tabepic** [comment]
Looking at pamac-cleancache.service, I see that it calls paccache -r, whereas pamac v6 calls pamac-clean-cache.
I don't think automatic cleaning works, as I've put five packages (same package, different versions) into the cache, set 4 as the threshold, and then tried opening/closing pamac, removing + reinstalling packages, and all five test packages stayed there.

**Comment by cromerc** [comment]
Have a look at pamac-cleancache.timer, this is the systemd file which controls when the cache is cleaned. By default it is set to 1 month. So the packages won't get cleaned up for a month. Try changing that to a smaller amount such as an hour. Then check back after an hour has passed to see if they got cleaned up.

**Comment by tabepic** [comment]
Alright, now it cleans (on the timer), leaving the last three packages.
However, the cache setting still doesn't save, so I can't change it to leave only the last package.

**Comment by cromerc** [comment]
After looking through the code, that setting is only used when manually cleaning the cache, it doesn't actually save nor use it for the auto cache cleaning service.

They did change this in pamac 6.0.0, they implemented cache cleaning with the configurable number of packages.

I will backport this feature into pamac classic.

**Comment by tabepic** [comment]
Okay, thanks. 
I'll wait until you finish backporting it before closing this issue.

**Comment by cromerc** [comment]
That's fine, I prefer to leave it open as a reminder to myself as well.
I will try to get to this soon, just been a little busy with implementing a customizeable build system, I need to make sure that is working well before I do this backport.

**Comment by tabepic** [comment]
Sounds great, take your time 😄 
(Can't wait for that customizable build system)

**Comment by cromerc** [comment]
I just pushed it a little bit ago(6.0.0). But it needs testing. The new 6.0.0 has a completely new build system based on AutoVala and CMake.

Here is an example PKGBUILD with the new build system:
https://gist.github.com/cromerc/e4f0e69a25d8f6a5fb26b201b741e855

Right now it only has a little bit of customizing available, you can disable AUR completely from Pamac by passing -DDISABLE_AUR to the cmake command in the build. Then the new binaries that are built won't have AUR for example. This allows people to build Pamac the way they want it. For Cromnix Linux Pamac will be built without AUR for example since it is a distro that is not compatible with the AUR.

The other option that it has is -DKDE_TRAY which instead of building the GTK3 tray, builds a tray for qt based interfaces like KDE and LXQT.

This is just a start, the idea is to add more customizing for the build process, then the packagers of Pamac would choose how they want it.

**Comment by tabepic** [comment]
I see, although I've just pushed an update to the AUR package.

Looking at the example, I see that you create a separate build directory; is this necessary, or just for cleanness?

Also, for some reason when I built the package I had to remove `/usr/share/icons/hicolor/icon-theme.cache` because it complained the file already existed - is there a more "correct" way of removing it other than just rm?

**Comment by cromerc** [comment]
I recommend using a build directory for cmake. Here are some links with info on reasons to do so:
http://cgold.readthedocs.io/en/latest/tutorials/out-of-source.html
http://voices.canonical.com/jussi.pakkanen/2013/04/16/why-you-should-consider-using-separate-build-directories/
The biggest reason for doing so is for multiple builds of the same project. For example imagine that you want to make a split PKGBUILD with 2 packages, pamac-classic and pamac-classic-aur, you would do this:
```
prepare() {
  mkdir build
  mkdir build-aur
}
build() {
  cd build
  cmake .. -DDISABLE_AUR
  cd ../build-aur
  cmake ..
}
package-pamac-classic() {
  cd build
  make install
}
package-pamac-classic-aur() {
  cd build-aur
  make install
}
```
This would build 2 packages with the one PKGBUILD file, 1 package with AUR and 1 without AUR for example.

Could you run:
`pacman -Qo /usr/share/icons/hicolor/icon-theme.cache`
When I built pamac 6.0.0 that file is not in my package... so I find it strange that it is in yours.
Did you build it with standard makepkg? Or are you using something else to build it? That file should not be in there.

**Comment by tabepic** [comment]
Sorry for the confusion;  I meant with my PKGBUILD, because it didn't specify `--pass-thru -DICON_UPDATE=OFF`

**Comment by cromerc** [comment]
Alright this feature is now backported via: 082f63603a08584ee9e9be9c283d6ae2d90d6065
