### ISSUE TITLE
One desktop file/application instead of two

### ISSUE THREAD

**Issue by tttom64** [cromnix/pamac-classic#6]
[manjaro/pamac #322](urlhttps://github.com/manjaro/pamac/issues/322)

Edit:  I saw this on the main page and thought it was a good idea. As a new user (~3 months ago) and now, having two shortcuts to open the same app never made sense to me.

**Comment by cromerc** [comment]
Fixed via: 705f49b80aa8e4da7a5271589b443929294a87e5
