### ISSUE TITLE
[Feature request] Allow editing of terminal fonts and colors

### ISSUE THREAD

**Issue by tttom64** [cromnix/pamac-classic#7]
### Problem:
Terminal colors and fonts look out of place.

### Solution:
Allow either:
* Customizing the colors directly in the preferences menu (like gnome-terminal) (preferred)
* Using system colors, at least for fg/bg colors (could be used in conjunction with above)
* Using colors from gnome-terminal or others if possible

### See also:
https://github.com/manjaro/pamac/issues/313
https://github.com/manjaro/pamac/issues/283
![screenshot from 2017-10-15 16-55-13](https://user-images.githubusercontent.com/13117753/31582239-8cb4708c-b16d-11e7-974a-6a74543ed714.png)
![screenshot from 2017-10-15 16-56-25](https://user-images.githubusercontent.com/13117753/31582242-b4528a98-b16d-11e7-80e3-99bd3eda6e8f.png)

**Comment by tabepic** [comment]
Agreed; this would be a great feature to add.

**Comment by cromerc** [comment]
I will try to take a look at it.

**Comment by cromerc** [comment]
I have added basic terminal color support: b47e208dd64cf7d9a1fde0328cf3048724371b9c

Please let me know if there are any issues with it.

**Comment by tttom64** [comment]
It seems to work fine. Do you plan on having all 16 colors supported?

**Comment by cromerc** [comment]
When you click on a color there is a + button that allows you to create custom colors. With rgb, you have 16777216 possible colors to pick from, way more than just 16. :wink:

**Comment by tttom64** [comment]
Oh sorry what I meant was editing the rest of the pallet like in gnome-terminal, not just text/background.

**Comment by cromerc** [comment]
I think that adding full terminal style support is a little too much considering that the idea behind pamac is to use a GUI and not a terminal for package management. The pamac.conf file would be huge and filled with just terminal options.

**Comment by tabepic** [comment]
I agree with you on the color, however would you consider adding a font option?

**Comment by cromerc** [comment]
@tabepic Already working on it. Should be finished soon.

**Comment by cromerc** [comment]
Fonts selection added: 6d72231ba1f76a4a9e963bde5d291d2f208fe1e9
