### ISSUE TITLE
Autostart desktop file points to wrong executable

### ISSUE THREAD

**Issue by gmes** [cromnix/pamac-classic#8]
When built with `--enable-kde-tray`, `pamac-tray-appindicator.desktop` is installed instead of `pamac-tray.desktop`.

`pamac-tray-appindicator.desktop` tries to execute `pamac-tray-appindicator`. However, this file doesn't exist, as the tray executable is still called `pamac-tray` when building with `--enable-kde-tray`.

This results in no tray icon appearing after launch.

**Comment by cromerc** [comment]
Thanks, fixed via: 1adbd17
